name: dino-tsugu
base: core24
version: '0.5.0'
summary: XMPP
description: |
  XMPP client

grade: stable
confinement: strict

lint:
  ignore:
    - classic
    - library

apps:
  dino-tsugu:
    command: main/dino
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib/x86_64-linux-gnu/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy
      HOME: "$SNAP_USER_DATA"
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - audio-playback
      - x11
      - wayland
      - unity7
      - desktop
      - desktop-legacy
      - password-manager-service
      - network-status

parts:
  dino-tsugu:
    source: .
    plugin: dump
    stage-packages:
      - valac
      - gettext
      - libgee-0.8-dev
      - libsqlite3-dev
      - libgtk-4-dev
      - libadwaita-1-0
      - libgpgme-dev
      - libsoup2.4-dev
      - libgcrypt20-dev
      - libqrencode-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libwebrtc-audio-processing-dev
      - libsrtp2-dev
      - libnice-dev
      - glib-networking
      - gstreamer1.0-plugins-good
      - libomemo-c-dev
      - libadwaita-1-dev
      - libproxy1v5
    
