name: dino-tsugu
base: core24
version: '0.5.0'
summary: XMPP messenger
description: |
  Dino is an XMPP messaging app for Linux using GTK and Vala. It supports calls, encryption, file transfers, group chats and more.

grade: stable
confinement: strict

lint:
  ignore:
    - classic
    - library


platforms:
  amd64:
  arm64:

slots:
  dino-tsugu-dbus-service:
    interface: dbus
    bus: session
    name: im.dino.Dino

apps:
  dino-tsugu:
    command: main/dino
    slots: [dino-tsugu-dbus-service]
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdino:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dino/plugins/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy
      HOME: "$SNAP_USER_DATA"
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - audio-playback
      - x11
      - wayland
      - unity7
      - desktop
      - desktop-legacy
      - password-manager-service
      - network-status
      - gpg-keys

parts:
  dino-tsugu:
    source: https://github.com/dino/dino/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/dino-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    source-type: tar
    plugin: meson
    build-packages:
      - meson
      - ninja-build
    stage-packages:
      - valac
      - gettext
      - libgee-0.8-dev
      - libsqlite3-dev
      - libgtk-4-dev
      - libadwaita-1-0
      - libgpgme-dev
      - libsoup2.4-dev
      - libgcrypt20-dev
      - libqrencode-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libwebrtc-audio-processing-dev
      - libsrtp2-dev
      - libnice-dev
      - glib-networking
      - gstreamer1.0-plugins-good
      - libomemo-c-dev
      - libadwaita-1-dev
      - libproxy1v5
    override-build: |
      set -e
      
      cd $CRAFT_PART_SRC
      
      meson setup build \
        -Dplugin-notification-sound=enabled \
        -Dplugin-rtp-h264=enabled \
        -Dplugin-rtp-vaapi=enabled \
        -Dplugin-rtp-vp9=enabled \
        -Dplugin-rtp-msdk=enabled
      
      meson compile -C build
      
      cp -r build/* $CRAFT_PART_INSTALL/
      
      ls -la $CRAFT_PART_INSTALL/
